spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/naeunserver
    username: sa
    password:
    driver-class-name: org.h2.Driver
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.springframework.security: DEBUG

jwt:
  secret: ZGF0ZW5hZXVuc2VydmVyU2VjcmV0UGFzc3dvcmRLZXkxMjM0c29va215dW5n