spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/date_naeun
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  profiles:
    include: API-KEY
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug